import Link from "next/link";
import { requireUser } from "@/lib/permissions";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function CollegeDashboard() {
  const user = await requireUser(["COLLEGE_HEAD", "COLLEGE_BRANCH"]);
  if (!user.collegeId) return <main className="account-content"><h1>Organization access is unavailable.</h1><Link href="/">Return home</Link></main>;
  const college = await prisma.college.findUnique({ where: { id: user.collegeId }, include: { branches: { ...(user.role === "COLLEGE_BRANCH" && user.branchId ? { where: { id: user.branchId } } : {}), orderBy: { name: "asc" }, include: { departments: { orderBy: { name: "asc" }, include: { offerings: { include: { university: true, courses: true } } } } } } } });
  if (!college) return <main className="account-content"><h1>Organization not found.</h1><Link href="/">Return home</Link></main>;
  return <main className="account-page"><header className="site-header"><Link className="brand" href="/"><span className="brand-mark">c</span><span>collytex</span></Link><nav className="main-nav"><Link href="/college">Dashboard</Link><Link href="/college/branches">Branches</Link><Link href="/college/courses">Courses</Link></nav><div className="header-actions"><span className="login-link">{user.name}</span><form action="/api/auth/logout" method="post"><button className="login-link logout-button">Log out</button></form></div></header><div className="account-content"><div className="eyebrow">{user.role === "COLLEGE_HEAD" ? "COLLEGE HEAD" : "BRANCH ACCOUNT"}</div><h1>{college.name}</h1><p>Manage your organization’s published information.</p><div className="status-banner"><span className="status-dot" /> Verification status: <b>{college.verificationStatus.toLowerCase()}</b>{college.verificationStatus !== "VERIFIED" && <small>Your college information stays private until verified by the platform team.</small>}</div><div className="account-section-heading"><h2>{user.role === "COLLEGE_HEAD" ? "Your campuses" : "Your campus"}</h2>{user.role === "COLLEGE_HEAD" && <Link className="text-link" href="/college/branches/new">Add a campus +</Link>}</div><div className="directory-list">{college.branches.map((branch) => <article className="directory-card" key={branch.id}><div className="directory-card-top"><div><span className="verified-label">{branch.isApproved ? "APPROVED BRANCH" : "AWAITING APPROVAL"}</span><h2>{branch.name}</h2><p className="branch-location">{branch.city}, {branch.state}</p></div><Link className="text-link" href={`/college/branches/${branch.id}`}>Manage campus ↗</Link></div><div className="directory-meta">{branch.departments.length} departments · {branch.departments.reduce((sum, department) => sum + department.offerings.reduce((count, offering) => count + offering.courses.length, 0), 0)} courses</div></article>)}{college.branches.length === 0 && <div className="empty-state"><span className="empty-mark">i</span><div><strong>No campuses added yet.</strong><p>Add your first campus to start building your college profile.</p></div></div>}</div></div></main>;
}
