import Link from "next/link";
import { requireUser } from "@/lib/permissions";
import { prisma } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function CompareCoursesPage() {
  const user = await requireUser(["STUDENT"]);
  const courses = await prisma.studentSavedCourse.findMany({ where: { userId: user.id, course: { offering: { department: { branch: { isApproved: true, college: { verificationStatus: "VERIFIED" } } } } } }, orderBy: { createdAt: "desc" }, take: 4, include: { course: { include: { offering: { include: { university: true, department: { include: { branch: { include: { college: true } } } } } }, fees: { orderBy: { academicYear: "desc" }, take: 1 }, placements: { orderBy: { academicYear: "desc" }, take: 1 } } } } });
  const money = (value: bigint | null | undefined) => value === null || value === undefined ? "Not provided" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value) / 100);
  return <main className="account-page"><header className="site-header"><Link className="brand" href="/student"><span className="brand-mark">c</span><span>collytex</span></Link><nav className="main-nav"><Link href="/explore">Explore colleges</Link><Link href="/student">Your shortlist</Link></nav></header><div className="account-content"><div className="eyebrow">YOUR SHORTLIST</div><h1>Compare courses.</h1><p>Compare up to four saved courses side by side. Figures are shown only when colleges have published them.</p>{courses.length < 2 ? <div className="empty-state"><div><strong>Save at least two courses to compare.</strong><p>Your saved courses will be ready here when you have a shortlist.</p></div><Link href="/explore">Explore courses →</Link></div> : <div className="compare-table-wrap"><table className="compare-table"><thead><tr><th>Course detail</th>{courses.map(({ course }) => <th key={course.id}><Link href={`/colleges/${course.offering.department.branch.college.slug}/${course.offering.department.branch.slug}/${course.offering.department.slug}/${course.offering.university.slug}/${course.slug}`}>{course.name}</Link><small>{course.offering.department.branch.college.name}</small></th>)}</tr></thead><tbody><tr><th>Campus</th>{courses.map(({ course }) => <td key={course.id}>{course.offering.department.branch.name}</td>)}</tr><tr><th>University</th>{courses.map(({ course }) => <td key={course.id}>{course.offering.university.name}</td>)}</tr><tr><th>Duration</th>{courses.map(({ course }) => <td key={course.id}>{course.durationYears ? `${course.durationYears} years` : "Not provided"}</td>)}</tr><tr><th>Latest fees</th>{courses.map(({ course }) => <td key={course.id}>{course.fees[0] ? <>{course.fees[0].academicYear}<br />{money(course.fees[0].amountPaise)}</> : "Not provided"}</td>)}</tr><tr><th>Latest average package</th>{courses.map(({ course }) => <td key={course.id}>{course.placements[0] ? <>{course.placements[0].academicYear}<br />{money(course.placements[0].averagePackagePaise)}</> : "Not provided"}</td>)}</tr><tr><th>Placement rate</th>{courses.map(({ course }) => <td key={course.id}>{course.placements[0]?.placementPercentage != null ? `${course.placements[0].placementPercentage}%` : "Not provided"}</td>)}</tr></tbody></table></div>}</div></main>;
}
